### PR TITLE
Config

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by firionavie-canary** [comment]
# rollout:*canary*

**Comment by firionavie-useast** [comment]
# rollout:*useast*

**Comment by firionavie-uswest** [comment]
# rollout:*uswest*

**Comment by firionavie-canary** [comment]
# rollout:*canary*

**Comment by firionavie-canary** [comment]
[rollout]: canary

**Comment by firionavie-canary** [comment]
[rollout]: canary

**Comment by firionavie-uswest** [comment]
[rollout]: uswest


## inprogress uswest - *In Progress*
---

###  `config/uswest/backend` - *Pending*


- [ ] configmap.v1 "default/backend-config-dgdf8mthck"

- [ ] service.v1 "default/backend-bar"

- [ ] service.v1 "default/backend-foo"

- [ ] deployment.extensions.v1beta1 "default/backend-bar"

- [ ] deployment.extensions.v1beta1 "default/backend-foo"

---
###  `config/uswest/frontend` - *Pending*


- [ ] configmap.v1 "default/frontend-config-7h5b4d5hmb"

- [ ] service.v1 "default/frontend-bar"

- [ ] service.v1 "default/frontend-foo"

- [ ] deployment.extensions.v1beta1 "default/frontend-bar"

- [ ] deployment.extensions.v1beta1 "default/frontend-foo"

---

**Comment by firionavie-useast** [comment]
[rollout]: useast

**Pull request merged**
