### PR TITLE
Revert "Revert "update config""

### PR DESCRIPTION
**Pull request by pwittrock**
Reverts pwittrock/najena#7

### CODE REVIEW

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:/v1/Service:default/helloworld1
rollout:devel
.v1.Service
default/helloworld1
```

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:/v1/Service:default/helloworld2
rollout:devel
.v1.Service
default/helloworld2
```

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:/v1/Service:default/helloworld3
rollout:devel
.v1.Service
default/helloworld3
```

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:extensions/v1beta1/Deployment:default/helloworld1
rollout:devel
extensions.v1beta1.Deployment
default/helloworld1
```

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:extensions/v1beta1/Deployment:default/helloworld2
rollout:devel
extensions.v1beta1.Deployment
default/helloworld2
```

**Comment by pwittrock** [comment]
### Rollout:

```rollout:devel:extensions/v1beta1/Deployment:default/helloworld3
rollout:devel
extensions.v1beta1.Deployment
default/helloworld3
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:/v1/Service:default/helloworld1
rollout:uswest
.v1.Service
default/helloworld1
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:/v1/Service:default/helloworld2
rollout:uswest
.v1.Service
default/helloworld2
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:/v1/Service:default/helloworld3
rollout:uswest
.v1.Service
default/helloworld3
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:extensions/v1beta1/Deployment:default/helloworld1
rollout:uswest
extensions.v1beta1.Deployment
default/helloworld1
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:extensions/v1beta1/Deployment:default/helloworld2
rollout:uswest
extensions.v1beta1.Deployment
default/helloworld2
```

**Comment by firionavie-uswest** [comment]
### Rollout:

```rollout:uswest:extensions/v1beta1/Deployment:default/helloworld3
rollout:uswest
extensions.v1beta1.Deployment
default/helloworld3
```

**Pull request merged**
